// <auto-generated />
using EURO2024Stat.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EURO2024Stat.DATA.Migrations
{
    [DbContext(typeof(PlayerContext))]
    partial class PlayerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EURO2024Stat.Domain.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<decimal>("FantasyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TshirtNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Age = 23,
                            CountryID = 1,
                            FantasyPrice = 100m,
                            Name = "Khvicha Kvaratskhelia",
                            Position = "Forward",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 2,
                            Age = 24,
                            CountryID = 1,
                            FantasyPrice = 100m,
                            Name = "Giorgi Mamardashvili",
                            Position = "GoalKeeper",
                            TshirtNumber = 25
                        },
                        new
                        {
                            ID = 3,
                            Age = 24,
                            CountryID = 1,
                            FantasyPrice = 100m,
                            Name = "Giorgi Mikautadze",
                            Position = "Forward",
                            TshirtNumber = 22
                        },
                        new
                        {
                            ID = 4,
                            Age = 25,
                            CountryID = 1,
                            FantasyPrice = 100m,
                            Name = "Giorgi Qochorashvili",
                            Position = "MidFielder",
                            TshirtNumber = 6
                        },
                        new
                        {
                            ID = 5,
                            Age = 34,
                            CountryID = 1,
                            FantasyPrice = 100m,
                            Name = "Guram Kashia",
                            Position = "Defender",
                            TshirtNumber = 4
                        },
                        new
                        {
                            ID = 6,
                            Age = 21,
                            CountryID = 2,
                            FantasyPrice = 100m,
                            Name = "Musiala",
                            Position = "Forward",
                            TshirtNumber = 14
                        },
                        new
                        {
                            ID = 7,
                            Age = 36,
                            CountryID = 2,
                            FantasyPrice = 100m,
                            Name = "Toni Kroos",
                            Position = "MidFielder",
                            TshirtNumber = 8
                        },
                        new
                        {
                            ID = 8,
                            Age = 28,
                            CountryID = 2,
                            FantasyPrice = 100m,
                            Name = "Joshua Kimmich",
                            Position = "MidFielder",
                            TshirtNumber = 6
                        },
                        new
                        {
                            ID = 9,
                            Age = 35,
                            CountryID = 2,
                            FantasyPrice = 100m,
                            Name = "Manuel Neuer",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 10,
                            Age = 33,
                            CountryID = 2,
                            FantasyPrice = 100m,
                            Name = "Mats Hummels",
                            Position = "Defender",
                            TshirtNumber = 5
                        },
                        new
                        {
                            ID = 11,
                            Age = 30,
                            CountryID = 3,
                            FantasyPrice = 7m,
                            Name = "Xherdan Shaqiri",
                            Position = "Forward",
                            TshirtNumber = 23
                        },
                        new
                        {
                            ID = 12,
                            Age = 33,
                            CountryID = 3,
                            FantasyPrice = 11m,
                            Name = "Yann Sommer",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 13,
                            Age = 30,
                            CountryID = 3,
                            FantasyPrice = 22m,
                            Name = "Granit Xhaka",
                            Position = "MidFielder",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 14,
                            Age = 29,
                            CountryID = 3,
                            FantasyPrice = 12m,
                            Name = "Ricardo Rodriguez",
                            Position = "Defender",
                            TshirtNumber = 13
                        },
                        new
                        {
                            ID = 15,
                            Age = 25,
                            CountryID = 3,
                            FantasyPrice = 12m,
                            Name = "Breel Embolo",
                            Position = "Forward",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 16,
                            Age = 28,
                            CountryID = 4,
                            FantasyPrice = 12m,
                            Name = "Andrew Robertson",
                            Position = "Defender",
                            TshirtNumber = 3
                        },
                        new
                        {
                            ID = 17,
                            Age = 25,
                            CountryID = 4,
                            FantasyPrice = 6m,
                            Name = "Scott McTominay",
                            Position = "MidFielder",
                            TshirtNumber = 6
                        },
                        new
                        {
                            ID = 18,
                            Age = 26,
                            CountryID = 4,
                            FantasyPrice = 11m,
                            Name = "John McGinn",
                            Position = "MidFielder",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 19,
                            Age = 25,
                            CountryID = 4,
                            FantasyPrice = 22m,
                            Name = "Che Adams",
                            Position = "Forward",
                            TshirtNumber = 9
                        },
                        new
                        {
                            ID = 20,
                            Age = 37,
                            CountryID = 4,
                            FantasyPrice = 12m,
                            Name = "David Marshall",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 21,
                            Age = 21,
                            CountryID = 5,
                            FantasyPrice = 20m,
                            Name = "Dominik Szoboszlai",
                            Position = "MidFielder",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 22,
                            Age = 28,
                            CountryID = 5,
                            FantasyPrice = 16m,
                            Name = "Willi Orban",
                            Position = "Defender",
                            TshirtNumber = 6
                        },
                        new
                        {
                            ID = 23,
                            Age = 31,
                            CountryID = 5,
                            FantasyPrice = 22m,
                            Name = "Peter Gulacsi",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 24,
                            Age = 33,
                            CountryID = 5,
                            FantasyPrice = 11m,
                            Name = "Adam Szalai",
                            Position = "Forward",
                            TshirtNumber = 9
                        },
                        new
                        {
                            ID = 25,
                            Age = 25,
                            CountryID = 5,
                            FantasyPrice = 16m,
                            Name = "Roland Sallai",
                            Position = "Forward",
                            TshirtNumber = 18
                        },
                        new
                        {
                            ID = 26,
                            Age = 33,
                            CountryID = 6,
                            FantasyPrice = 100m,
                            Name = "Sergio Busquets",
                            Position = "MidFielder",
                            TshirtNumber = 5
                        },
                        new
                        {
                            ID = 27,
                            Age = 29,
                            CountryID = 6,
                            FantasyPrice = 100m,
                            Name = "Gerard Moreno",
                            Position = "Forward",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 28,
                            Age = 32,
                            CountryID = 6,
                            FantasyPrice = 100m,
                            Name = "Jordi Alba",
                            Position = "Defender",
                            TshirtNumber = 18
                        },
                        new
                        {
                            ID = 29,
                            Age = 30,
                            CountryID = 6,
                            FantasyPrice = 100m,
                            Name = "David de Gea",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 30,
                            Age = 30,
                            CountryID = 6,
                            FantasyPrice = 100m,
                            Name = "Thiago Alcantara",
                            Position = "MidFielder",
                            TshirtNumber = 8
                        },
                        new
                        {
                            ID = 31,
                            Age = 22,
                            CountryID = 7,
                            FantasyPrice = 100m,
                            Name = "Gianluigi Donnarumma",
                            Position = "GoalKeeper",
                            TshirtNumber = 21
                        },
                        new
                        {
                            ID = 32,
                            Age = 34,
                            CountryID = 7,
                            FantasyPrice = 100m,
                            Name = "Leonardo Bonucci",
                            Position = "Defender",
                            TshirtNumber = 19
                        },
                        new
                        {
                            ID = 33,
                            Age = 30,
                            CountryID = 7,
                            FantasyPrice = 100m,
                            Name = "Jorginho",
                            Position = "MidFielder",
                            TshirtNumber = 8
                        },
                        new
                        {
                            ID = 34,
                            Age = 31,
                            CountryID = 7,
                            FantasyPrice = 100m,
                            Name = "Ciro Immobile",
                            Position = "Forward",
                            TshirtNumber = 17
                        },
                        new
                        {
                            ID = 35,
                            Age = 30,
                            CountryID = 7,
                            FantasyPrice = 100m,
                            Name = "Lorenzo Insigne",
                            Position = "Forward",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 36,
                            Age = 32,
                            CountryID = 8,
                            FantasyPrice = 4m,
                            Name = "Etrit Berisha",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 37,
                            Age = 27,
                            CountryID = 8,
                            FantasyPrice = 5m,
                            Name = "Elseid Hysaj",
                            Position = "Defender",
                            TshirtNumber = 23
                        },
                        new
                        {
                            ID = 38,
                            Age = 30,
                            CountryID = 8,
                            FantasyPrice = 12m,
                            Name = "Odise Roshi",
                            Position = "Forward",
                            TshirtNumber = 11
                        },
                        new
                        {
                            ID = 39,
                            Age = 24,
                            CountryID = 8,
                            FantasyPrice = 5m,
                            Name = "Keidi Bare",
                            Position = "MidFielder",
                            TshirtNumber = 18
                        },
                        new
                        {
                            ID = 40,
                            Age = 31,
                            CountryID = 8,
                            FantasyPrice = 5m,
                            Name = "Sokol Cikalleshi",
                            Position = "Forward",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 41,
                            Age = 35,
                            CountryID = 9,
                            FantasyPrice = 100m,
                            Name = "Luka Modric",
                            Position = "MidFielder",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 42,
                            Age = 32,
                            CountryID = 9,
                            FantasyPrice = 33m,
                            Name = "Ivan Perisic",
                            Position = "Forward",
                            TshirtNumber = 4
                        },
                        new
                        {
                            ID = 43,
                            Age = 32,
                            CountryID = 9,
                            FantasyPrice = 22m,
                            Name = "Domagoj Vida",
                            Position = "Defender",
                            TshirtNumber = 21
                        },
                        new
                        {
                            ID = 44,
                            Age = 27,
                            CountryID = 9,
                            FantasyPrice = 11m,
                            Name = "Mateo Kovacic",
                            Position = "MidFielder",
                            TshirtNumber = 8
                        },
                        new
                        {
                            ID = 45,
                            Age = 20,
                            CountryID = 9,
                            FantasyPrice = 22m,
                            Name = "Josko Gvardiol",
                            Position = "Defender",
                            TshirtNumber = 14
                        },
                        new
                        {
                            ID = 46,
                            Age = 28,
                            CountryID = 10,
                            FantasyPrice = 100m,
                            Name = "Harry Kane",
                            Position = "Forward",
                            TshirtNumber = 9
                        },
                        new
                        {
                            ID = 47,
                            Age = 28,
                            CountryID = 10,
                            FantasyPrice = 100m,
                            Name = "Jordan Pickford",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 48,
                            Age = 28,
                            CountryID = 10,
                            FantasyPrice = 78m,
                            Name = "Raheem Sterling",
                            Position = "Forward",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 49,
                            Age = 23,
                            CountryID = 10,
                            FantasyPrice = 20m,
                            Name = "Declan Rice",
                            Position = "MidFielder",
                            TshirtNumber = 4
                        },
                        new
                        {
                            ID = 50,
                            Age = 29,
                            CountryID = 10,
                            FantasyPrice = 30m,
                            Name = "Harry Maguire",
                            Position = "Defender",
                            TshirtNumber = 6
                        },
                        new
                        {
                            ID = 51,
                            Age = 30,
                            CountryID = 11,
                            FantasyPrice = 75m,
                            Name = "Christian Eriksen",
                            Position = "MidFielder",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 52,
                            Age = 35,
                            CountryID = 11,
                            FantasyPrice = 23m,
                            Name = "Kasper Schmeichel",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 53,
                            Age = 25,
                            CountryID = 11,
                            FantasyPrice = 60m,
                            Name = "Andreas Christensen",
                            Position = "Defender",
                            TshirtNumber = 6
                        },
                        new
                        {
                            ID = 54,
                            Age = 27,
                            CountryID = 11,
                            FantasyPrice = 12m,
                            Name = "Yussuf Poulsen",
                            Position = "Forward",
                            TshirtNumber = 20
                        },
                        new
                        {
                            ID = 55,
                            Age = 25,
                            CountryID = 11,
                            FantasyPrice = 33m,
                            Name = "Pierre-Emile Hojbjerg",
                            Position = "MidFielder",
                            TshirtNumber = 5
                        },
                        new
                        {
                            ID = 56,
                            Age = 29,
                            CountryID = 12,
                            FantasyPrice = 10m,
                            Name = "Jan Oblak",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 57,
                            Age = 33,
                            CountryID = 12,
                            FantasyPrice = 12m,
                            Name = "Josip Ilicic",
                            Position = "Forward",
                            TshirtNumber = 9
                        },
                        new
                        {
                            ID = 58,
                            Age = 27,
                            CountryID = 12,
                            FantasyPrice = 33m,
                            Name = "Benjamin Verbic",
                            Position = "MidFielder",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 59,
                            Age = 31,
                            CountryID = 12,
                            FantasyPrice = 22m,
                            Name = "Miha Mevlja",
                            Position = "Defender",
                            TshirtNumber = 6
                        },
                        new
                        {
                            ID = 60,
                            Age = 29,
                            CountryID = 12,
                            FantasyPrice = 12m,
                            Name = "Haris Vuckic",
                            Position = "MidFielder",
                            TshirtNumber = 11
                        },
                        new
                        {
                            ID = 61,
                            Age = 33,
                            CountryID = 13,
                            FantasyPrice = 28m,
                            Name = "Nemanja Matic",
                            Position = "MidFielder",
                            TshirtNumber = 21
                        },
                        new
                        {
                            ID = 62,
                            Age = 32,
                            CountryID = 13,
                            FantasyPrice = 30m,
                            Name = "Dusan Tadic",
                            Position = "Forward",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 63,
                            Age = 27,
                            CountryID = 13,
                            FantasyPrice = 65m,
                            Name = "Aleksandar Mitrovic",
                            Position = "Forward",
                            TshirtNumber = 9
                        },
                        new
                        {
                            ID = 64,
                            Age = 32,
                            CountryID = 13,
                            FantasyPrice = 22m,
                            Name = "Stefan Mitrovic",
                            Position = "Defender",
                            TshirtNumber = 13
                        },
                        new
                        {
                            ID = 65,
                            Age = 27,
                            CountryID = 13,
                            FantasyPrice = 33m,
                            Name = "Sergej Milinkovic-Savic",
                            Position = "MidFielder",
                            TshirtNumber = 20
                        },
                        new
                        {
                            ID = 66,
                            Age = 28,
                            CountryID = 14,
                            FantasyPrice = 80m,
                            Name = "Memphis Depay",
                            Position = "Forward",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 67,
                            Age = 30,
                            CountryID = 14,
                            FantasyPrice = 35m,
                            Name = "Georginio Wijnaldum",
                            Position = "MidFielder",
                            TshirtNumber = 8
                        },
                        new
                        {
                            ID = 68,
                            Age = 23,
                            CountryID = 14,
                            FantasyPrice = 78m,
                            Name = "Matthijs de Ligt",
                            Position = "Defender",
                            TshirtNumber = 3
                        },
                        new
                        {
                            ID = 69,
                            Age = 25,
                            CountryID = 14,
                            FantasyPrice = 50m,
                            Name = "Denzel Dumfries",
                            Position = "Defender",
                            TshirtNumber = 22
                        },
                        new
                        {
                            ID = 70,
                            Age = 25,
                            CountryID = 14,
                            FantasyPrice = 100m,
                            Name = "Frenkie de Jong",
                            Position = "MidFielder",
                            TshirtNumber = 21
                        },
                        new
                        {
                            ID = 71,
                            Age = 23,
                            CountryID = 15,
                            FantasyPrice = 200m,
                            Name = "Kylian Mbappe",
                            Position = "Forward",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 72,
                            Age = 30,
                            CountryID = 15,
                            FantasyPrice = 100m,
                            Name = "Antoine Griezmann",
                            Position = "Forward",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 73,
                            Age = 30,
                            CountryID = 15,
                            FantasyPrice = 60m,
                            Name = "Paul Pogba",
                            Position = "MidFielder",
                            TshirtNumber = 6
                        },
                        new
                        {
                            ID = 74,
                            Age = 28,
                            CountryID = 15,
                            FantasyPrice = 100m,
                            Name = "Raphael Varane",
                            Position = "Defender",
                            TshirtNumber = 4
                        },
                        new
                        {
                            ID = 75,
                            Age = 35,
                            CountryID = 15,
                            FantasyPrice = 100m,
                            Name = "Hugo Lloris",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 76,
                            Age = 29,
                            CountryID = 16,
                            FantasyPrice = 100m,
                            Name = "David Alaba",
                            Position = "Defender",
                            TshirtNumber = 8
                        },
                        new
                        {
                            ID = 77,
                            Age = 32,
                            CountryID = 16,
                            FantasyPrice = 70m,
                            Name = "Marko Arnautovic",
                            Position = "Forward",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 78,
                            Age = 27,
                            CountryID = 16,
                            FantasyPrice = 23m,
                            Name = "Marcel Sabitzer",
                            Position = "MidFielder",
                            TshirtNumber = 9
                        },
                        new
                        {
                            ID = 79,
                            Age = 29,
                            CountryID = 16,
                            FantasyPrice = 11m,
                            Name = "Stefan Lainer",
                            Position = "Defender",
                            TshirtNumber = 22
                        },
                        new
                        {
                            ID = 80,
                            Age = 24,
                            CountryID = 16,
                            FantasyPrice = 22m,
                            Name = "Konrad Laimer",
                            Position = "MidFielder",
                            TshirtNumber = 14
                        },
                        new
                        {
                            ID = 81,
                            Age = 32,
                            CountryID = 17,
                            FantasyPrice = 80m,
                            Name = "Robert Lewandowski",
                            Position = "Forward",
                            TshirtNumber = 9
                        },
                        new
                        {
                            ID = 82,
                            Age = 31,
                            CountryID = 17,
                            FantasyPrice = 22m,
                            Name = "Wojciech Szczesny",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 83,
                            Age = 28,
                            CountryID = 17,
                            FantasyPrice = 33m,
                            Name = "Arkadiusz Milik",
                            Position = "Forward",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 84,
                            Age = 33,
                            CountryID = 17,
                            FantasyPrice = 11m,
                            Name = "Kamil Glik",
                            Position = "Defender",
                            TshirtNumber = 15
                        },
                        new
                        {
                            ID = 85,
                            Age = 27,
                            CountryID = 17,
                            FantasyPrice = 25m,
                            Name = "Piotr Zielinski",
                            Position = "MidFielder",
                            TshirtNumber = 19
                        },
                        new
                        {
                            ID = 86,
                            Age = 23,
                            CountryID = 18,
                            FantasyPrice = 12m,
                            Name = "Ianis Hagi",
                            Position = "MidFielder",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 87,
                            Age = 28,
                            CountryID = 18,
                            FantasyPrice = 7m,
                            Name = "Florin Andone",
                            Position = "Forward",
                            TshirtNumber = 11
                        },
                        new
                        {
                            ID = 88,
                            Age = 34,
                            CountryID = 18,
                            FantasyPrice = 8m,
                            Name = "Ciprian Tatarusanu",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 89,
                            Age = 32,
                            CountryID = 18,
                            FantasyPrice = 11m,
                            Name = "Vlad Chiriches",
                            Position = "Defender",
                            TshirtNumber = 3
                        },
                        new
                        {
                            ID = 90,
                            Age = 26,
                            CountryID = 18,
                            FantasyPrice = 22m,
                            Name = "Alexandru Mitrita",
                            Position = "Forward",
                            TshirtNumber = 20
                        },
                        new
                        {
                            ID = 91,
                            Age = 30,
                            CountryID = 19,
                            FantasyPrice = 100m,
                            Name = "Kevin De Bruyne",
                            Position = "MidFielder",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 92,
                            Age = 28,
                            CountryID = 19,
                            FantasyPrice = 100m,
                            Name = "Romelu Lukaku",
                            Position = "Forward",
                            TshirtNumber = 9
                        },
                        new
                        {
                            ID = 93,
                            Age = 31,
                            CountryID = 19,
                            FantasyPrice = 100m,
                            Name = "Thibaut Courtois",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 94,
                            Age = 33,
                            CountryID = 19,
                            FantasyPrice = 44m,
                            Name = "Toby Alderweireld",
                            Position = "Defender",
                            TshirtNumber = 2
                        },
                        new
                        {
                            ID = 95,
                            Age = 25,
                            CountryID = 19,
                            FantasyPrice = 35m,
                            Name = "Youri Tielemans",
                            Position = "MidFielder",
                            TshirtNumber = 8
                        },
                        new
                        {
                            ID = 96,
                            Age = 27,
                            CountryID = 20,
                            FantasyPrice = 22m,
                            Name = "Milan Skriniar",
                            Position = "Defender",
                            TshirtNumber = 14
                        },
                        new
                        {
                            ID = 97,
                            Age = 32,
                            CountryID = 20,
                            FantasyPrice = 12m,
                            Name = "Martin Dubravka",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 98,
                            Age = 34,
                            CountryID = 20,
                            FantasyPrice = 66m,
                            Name = "Juraj Kucka",
                            Position = "MidFielder",
                            TshirtNumber = 19
                        },
                        new
                        {
                            ID = 99,
                            Age = 30,
                            CountryID = 20,
                            FantasyPrice = 34m,
                            Name = "Robert Mak",
                            Position = "MidFielder",
                            TshirtNumber = 20
                        },
                        new
                        {
                            ID = 100,
                            Age = 26,
                            CountryID = 20,
                            FantasyPrice = 17m,
                            Name = "Ondrej Duda",
                            Position = "Forward",
                            TshirtNumber = 22
                        },
                        new
                        {
                            ID = 101,
                            Age = 32,
                            CountryID = 21,
                            FantasyPrice = 40m,
                            Name = "Andriy Yarmolenko",
                            Position = "Forward",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 102,
                            Age = 25,
                            CountryID = 21,
                            FantasyPrice = 60m,
                            Name = "Oleksandr Zinchenko",
                            Position = "MidFielder",
                            TshirtNumber = 17
                        },
                        new
                        {
                            ID = 103,
                            Age = 25,
                            CountryID = 21,
                            FantasyPrice = 34m,
                            Name = "Mykola Matviyenko",
                            Position = "Defender",
                            TshirtNumber = 22
                        },
                        new
                        {
                            ID = 104,
                            Age = 37,
                            CountryID = 21,
                            FantasyPrice = 100m,
                            Name = "Andriy Pyatov",
                            Position = "GoalKeeper",
                            TshirtNumber = 12
                        },
                        new
                        {
                            ID = 105,
                            Age = 26,
                            CountryID = 21,
                            FantasyPrice = 30m,
                            Name = "Roman Yaremchuk",
                            Position = "Forward",
                            TshirtNumber = 9
                        },
                        new
                        {
                            ID = 106,
                            Age = 39,
                            CountryID = 22,
                            FantasyPrice = 100m,
                            Name = "Cristiano Ronaldo",
                            Position = "Forward",
                            TshirtNumber = 7
                        },
                        new
                        {
                            ID = 107,
                            Age = 29,
                            CountryID = 22,
                            FantasyPrice = 100m,
                            Name = "Bruno Fernandes",
                            Position = "MidFielder",
                            TshirtNumber = 8
                        },
                        new
                        {
                            ID = 108,
                            Age = 26,
                            CountryID = 22,
                            FantasyPrice = 100m,
                            Name = "Ruben Dias",
                            Position = "Defender",
                            TshirtNumber = 3
                        },
                        new
                        {
                            ID = 109,
                            Age = 36,
                            CountryID = 22,
                            FantasyPrice = 50m,
                            Name = "Rui Patricio",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 110,
                            Age = 23,
                            CountryID = 22,
                            FantasyPrice = 70m,
                            Name = "Joao Felix",
                            Position = "Forward",
                            TshirtNumber = 21
                        },
                        new
                        {
                            ID = 111,
                            Age = 36,
                            CountryID = 23,
                            FantasyPrice = 11m,
                            Name = "Burak Yilmaz",
                            Position = "Forward",
                            TshirtNumber = 17
                        },
                        new
                        {
                            ID = 112,
                            Age = 28,
                            CountryID = 23,
                            FantasyPrice = 70m,
                            Name = "Hakan Calhanoglu",
                            Position = "MidFielder",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 113,
                            Age = 24,
                            CountryID = 23,
                            FantasyPrice = 20m,
                            Name = "Merih Demiral",
                            Position = "Defender",
                            TshirtNumber = 3
                        },
                        new
                        {
                            ID = 114,
                            Age = 26,
                            CountryID = 23,
                            FantasyPrice = 20m,
                            Name = "Ugurcan Cakir",
                            Position = "GoalKeeper",
                            TshirtNumber = 23
                        },
                        new
                        {
                            ID = 115,
                            Age = 24,
                            CountryID = 23,
                            FantasyPrice = 22m,
                            Name = "Cengiz Under",
                            Position = "Forward",
                            TshirtNumber = 17
                        },
                        new
                        {
                            ID = 116,
                            Age = 27,
                            CountryID = 24,
                            FantasyPrice = 5m,
                            Name = "Tomas Soucek",
                            Position = "MidFielder",
                            TshirtNumber = 15
                        },
                        new
                        {
                            ID = 117,
                            Age = 26,
                            CountryID = 24,
                            FantasyPrice = 8m,
                            Name = "Patrik Schick",
                            Position = "Forward",
                            TshirtNumber = 10
                        },
                        new
                        {
                            ID = 118,
                            Age = 32,
                            CountryID = 24,
                            FantasyPrice = 10m,
                            Name = "Tomas Vaclik",
                            Position = "GoalKeeper",
                            TshirtNumber = 1
                        },
                        new
                        {
                            ID = 119,
                            Age = 29,
                            CountryID = 24,
                            FantasyPrice = 8m,
                            Name = "Vladimir Coufal",
                            Position = "Defender",
                            TshirtNumber = 5
                        },
                        new
                        {
                            ID = 120,
                            Age = 27,
                            CountryID = 24,
                            FantasyPrice = 10m,
                            Name = "Antonin Barak",
                            Position = "MidFielder",
                            TshirtNumber = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
