// <auto-generated />
using System;
using EURO2024Stat.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EURO2024Stat.DATA.Migrations.Match
{
    [DbContext(typeof(MatchContext))]
    [Migration("20240624124202_matchresulttbl")]
    partial class matchresulttbl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EURO2024Stat.Domain.MatchResults", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("MatchID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MatchID")
                        .IsUnique();

                    b.ToTable("MatchResults");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 1
                        },
                        new
                        {
                            ID = 2,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 2
                        },
                        new
                        {
                            ID = 3,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 3
                        },
                        new
                        {
                            ID = 4,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 4
                        },
                        new
                        {
                            ID = 5,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 5
                        },
                        new
                        {
                            ID = 6,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 6
                        },
                        new
                        {
                            ID = 7,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 7
                        },
                        new
                        {
                            ID = 8,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 8
                        },
                        new
                        {
                            ID = 9,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 9
                        },
                        new
                        {
                            ID = 10,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 10
                        },
                        new
                        {
                            ID = 11,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 11
                        },
                        new
                        {
                            ID = 12,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 12
                        },
                        new
                        {
                            ID = 13,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 13
                        },
                        new
                        {
                            ID = 14,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 14
                        },
                        new
                        {
                            ID = 15,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 15
                        },
                        new
                        {
                            ID = 16,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 16
                        },
                        new
                        {
                            ID = 17,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 17
                        },
                        new
                        {
                            ID = 18,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 18
                        },
                        new
                        {
                            ID = 19,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 19
                        },
                        new
                        {
                            ID = 20,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 20
                        },
                        new
                        {
                            ID = 21,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 21
                        },
                        new
                        {
                            ID = 22,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 22
                        },
                        new
                        {
                            ID = 23,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 23
                        },
                        new
                        {
                            ID = 24,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 24
                        },
                        new
                        {
                            ID = 25,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 25
                        },
                        new
                        {
                            ID = 26,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 26
                        },
                        new
                        {
                            ID = 27,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 27
                        },
                        new
                        {
                            ID = 28,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 28
                        },
                        new
                        {
                            ID = 29,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 29
                        },
                        new
                        {
                            ID = 30,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 30
                        },
                        new
                        {
                            ID = 31,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 31
                        },
                        new
                        {
                            ID = 32,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 32
                        },
                        new
                        {
                            ID = 33,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 33
                        },
                        new
                        {
                            ID = 34,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 34
                        },
                        new
                        {
                            ID = 35,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 35
                        },
                        new
                        {
                            ID = 36,
                            AwayScore = 0,
                            HomeScore = 0,
                            MatchID = 36
                        });
                });

            modelBuilder.Entity("EURO2024Stat.Domain.Matches", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AwayCountryID")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeCountryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatchDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stadium")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AwayCountryID = 4,
                            Group = "A",
                            HomeCountryID = 2,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 14, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Allianz Arena, Munich"
                        },
                        new
                        {
                            ID = 2,
                            AwayCountryID = 5,
                            Group = "A",
                            HomeCountryID = 3,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Olympiastadion, Berlin"
                        },
                        new
                        {
                            ID = 3,
                            AwayCountryID = 5,
                            Group = "A",
                            HomeCountryID = 2,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Allianz Arena, Munich"
                        },
                        new
                        {
                            ID = 4,
                            AwayCountryID = 3,
                            Group = "A",
                            HomeCountryID = 4,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 21, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Mercedes-Benz Arena, Stuttgart"
                        },
                        new
                        {
                            ID = 5,
                            AwayCountryID = 3,
                            Group = "A",
                            HomeCountryID = 2,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 25, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Volksparkstadion, Hamburg"
                        },
                        new
                        {
                            ID = 6,
                            AwayCountryID = 5,
                            Group = "A",
                            HomeCountryID = 4,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Olympiastadion, Berlin"
                        },
                        new
                        {
                            ID = 7,
                            AwayCountryID = 9,
                            Group = "B",
                            HomeCountryID = 6,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Mercedes-Benz Arena, Stuttgart"
                        },
                        new
                        {
                            ID = 8,
                            AwayCountryID = 8,
                            Group = "B",
                            HomeCountryID = 7,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "RheinEnergieStadion, Cologne"
                        },
                        new
                        {
                            ID = 9,
                            AwayCountryID = 8,
                            Group = "B",
                            HomeCountryID = 6,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Olympiastadion, Berlin"
                        },
                        new
                        {
                            ID = 10,
                            AwayCountryID = 7,
                            Group = "B",
                            HomeCountryID = 9,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 21, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Allianz Arena, Munich"
                        },
                        new
                        {
                            ID = 11,
                            AwayCountryID = 7,
                            Group = "B",
                            HomeCountryID = 6,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Volksparkstadion, Hamburg"
                        },
                        new
                        {
                            ID = 12,
                            AwayCountryID = 8,
                            Group = "B",
                            HomeCountryID = 9,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 26, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Mercedes-Benz Arena, Stuttgart"
                        },
                        new
                        {
                            ID = 13,
                            AwayCountryID = 12,
                            Group = "C",
                            HomeCountryID = 10,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Veltins-Arena, Gelsenkirchen"
                        },
                        new
                        {
                            ID = 14,
                            AwayCountryID = 13,
                            Group = "C",
                            HomeCountryID = 11,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Volksparkstadion, Hamburg"
                        },
                        new
                        {
                            ID = 15,
                            AwayCountryID = 13,
                            Group = "C",
                            HomeCountryID = 10,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 22, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Commerzbank-Arena, Frankfurt"
                        },
                        new
                        {
                            ID = 16,
                            AwayCountryID = 11,
                            Group = "C",
                            HomeCountryID = 12,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 23, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Volksparkstadion, Hamburg"
                        },
                        new
                        {
                            ID = 17,
                            AwayCountryID = 11,
                            Group = "C",
                            HomeCountryID = 10,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 27, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Veltins-Arena, Gelsenkirchen"
                        },
                        new
                        {
                            ID = 18,
                            AwayCountryID = 13,
                            Group = "C",
                            HomeCountryID = 12,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 28, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Commerzbank-Arena, Frankfurt"
                        },
                        new
                        {
                            ID = 19,
                            AwayCountryID = 17,
                            Group = "D",
                            HomeCountryID = 14,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Red Bull Arena, Leipzig"
                        },
                        new
                        {
                            ID = 20,
                            AwayCountryID = 16,
                            Group = "D",
                            HomeCountryID = 15,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Esprit Arena, Düsseldorf"
                        },
                        new
                        {
                            ID = 21,
                            AwayCountryID = 16,
                            Group = "D",
                            HomeCountryID = 14,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 21, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Red Bull Arena, Leipzig"
                        },
                        new
                        {
                            ID = 22,
                            AwayCountryID = 15,
                            Group = "D",
                            HomeCountryID = 17,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Esprit Arena, Düsseldorf"
                        },
                        new
                        {
                            ID = 23,
                            AwayCountryID = 15,
                            Group = "D",
                            HomeCountryID = 14,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Commerzbank-Arena, Frankfurt"
                        },
                        new
                        {
                            ID = 24,
                            AwayCountryID = 16,
                            Group = "D",
                            HomeCountryID = 17,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 27, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Red Bull Arena, Leipzig"
                        },
                        new
                        {
                            ID = 25,
                            AwayCountryID = 21,
                            Group = "E",
                            HomeCountryID = 18,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Mercedes-Benz Arena, Stuttgart"
                        },
                        new
                        {
                            ID = 26,
                            AwayCountryID = 20,
                            Group = "E",
                            HomeCountryID = 19,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 18, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Commerzbank-Arena, Frankfurt"
                        },
                        new
                        {
                            ID = 27,
                            AwayCountryID = 20,
                            Group = "E",
                            HomeCountryID = 18,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 23, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Red Bull Arena, Leipzig"
                        },
                        new
                        {
                            ID = 28,
                            AwayCountryID = 19,
                            Group = "E",
                            HomeCountryID = 21,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 23, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Olympiastadion, Berlin"
                        },
                        new
                        {
                            ID = 29,
                            AwayCountryID = 19,
                            Group = "E",
                            HomeCountryID = 18,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 28, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Esprit Arena, Düsseldorf"
                        },
                        new
                        {
                            ID = 30,
                            AwayCountryID = 20,
                            Group = "E",
                            HomeCountryID = 21,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 28, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Mercedes-Benz Arena, Stuttgart"
                        },
                        new
                        {
                            ID = 31,
                            AwayCountryID = 23,
                            Group = "F",
                            HomeCountryID = 22,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "RheinEnergieStadion, Cologne"
                        },
                        new
                        {
                            ID = 32,
                            AwayCountryID = 24,
                            Group = "F",
                            HomeCountryID = 1,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 18, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Red Bull Arena, Leipzig"
                        },
                        new
                        {
                            ID = 33,
                            AwayCountryID = 24,
                            Group = "F",
                            HomeCountryID = 22,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 23, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Mercedes-Benz Arena, Stuttgart"
                        },
                        new
                        {
                            ID = 34,
                            AwayCountryID = 1,
                            Group = "F",
                            HomeCountryID = 23,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 23, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Allianz Arena, Munich"
                        },
                        new
                        {
                            ID = 35,
                            AwayCountryID = 1,
                            Group = "F",
                            HomeCountryID = 22,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 27, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Volksparkstadion, Hamburg"
                        },
                        new
                        {
                            ID = 36,
                            AwayCountryID = 24,
                            Group = "F",
                            HomeCountryID = 23,
                            IsFinished = false,
                            MatchDatetime = new DateTime(2024, 6, 27, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Olympiastadion, Berlin"
                        });
                });

            modelBuilder.Entity("EURO2024Stat.Domain.MatchResults", b =>
                {
                    b.HasOne("EURO2024Stat.Domain.Matches", "Match")
                        .WithOne("MatchResults")
                        .HasForeignKey("EURO2024Stat.Domain.MatchResults", "MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("EURO2024Stat.Domain.Matches", b =>
                {
                    b.Navigation("MatchResults");
                });
#pragma warning restore 612, 618
        }
    }
}
