// <auto-generated />
using System;
using EURO2024Stat.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EURO2024Stat.DATA.Migrations.Bet
{
    [DbContext(typeof(BetContext))]
    [Migration("20240627080702_addbetting")]
    partial class addbetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EURO2024Stat.Domain.Bet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("BetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BetID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BetStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatePlaced")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("EURO2024Stat.Domain.BetMatches", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AwayCoefficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AwayCountryId")
                        .HasColumnType("int");

                    b.Property<string>("AwayCountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DrawCoefficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HomeCoefficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HomeCountryId")
                        .HasColumnType("int");

                    b.Property<string>("HomeCountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<bool>("isFinished")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("BetMatches");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AwayCoefficient = 5.6m,
                            AwayCountryId = 4,
                            AwayCountryName = "Scotland",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.4m,
                            HomeCountryId = 2,
                            HomeCountryName = "Germany",
                            MatchId = 1,
                            isFinished = false
                        },
                        new
                        {
                            ID = 2,
                            AwayCoefficient = 3.2m,
                            AwayCountryId = 5,
                            AwayCountryName = "Hungary",
                            DrawCoefficient = 3.5m,
                            HomeCoefficient = 1.7m,
                            HomeCountryId = 3,
                            HomeCountryName = "Switzerland",
                            MatchId = 2,
                            isFinished = false
                        },
                        new
                        {
                            ID = 3,
                            AwayCoefficient = 8.0m,
                            AwayCountryId = 5,
                            AwayCountryName = "Hungary",
                            DrawCoefficient = 3.0m,
                            HomeCoefficient = 1.6m,
                            HomeCountryId = 2,
                            HomeCountryName = "Germany",
                            MatchId = 3,
                            isFinished = false
                        },
                        new
                        {
                            ID = 4,
                            AwayCoefficient = 1.95m,
                            AwayCountryId = 3,
                            AwayCountryName = "Switzerland",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 3.0m,
                            HomeCountryId = 4,
                            HomeCountryName = "Scotnald",
                            MatchId = 4,
                            isFinished = false
                        },
                        new
                        {
                            ID = 5,
                            AwayCoefficient = 3.5m,
                            AwayCountryId = 3,
                            AwayCountryName = "Switzerland",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.5m,
                            HomeCountryId = 2,
                            HomeCountryName = "Germany",
                            MatchId = 5,
                            isFinished = false
                        },
                        new
                        {
                            ID = 6,
                            AwayCoefficient = 2.95m,
                            AwayCountryId = 5,
                            AwayCountryName = "Hungary",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 1.85m,
                            HomeCountryId = 4,
                            HomeCountryName = "Scotland",
                            MatchId = 6,
                            isFinished = false
                        },
                        new
                        {
                            ID = 7,
                            AwayCoefficient = 5.6m,
                            AwayCountryId = 9,
                            AwayCountryName = "Croatia",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.4m,
                            HomeCountryId = 6,
                            HomeCountryName = "Spain",
                            MatchId = 7,
                            isFinished = false
                        },
                        new
                        {
                            ID = 8,
                            AwayCoefficient = 3.2m,
                            AwayCountryId = 8,
                            AwayCountryName = "Albania",
                            DrawCoefficient = 3.5m,
                            HomeCoefficient = 1.7m,
                            HomeCountryId = 7,
                            HomeCountryName = "Italy",
                            MatchId = 8,
                            isFinished = false
                        },
                        new
                        {
                            ID = 9,
                            AwayCoefficient = 8.0m,
                            AwayCountryId = 8,
                            AwayCountryName = "Albania",
                            DrawCoefficient = 3.0m,
                            HomeCoefficient = 1.6m,
                            HomeCountryId = 6,
                            HomeCountryName = "Spain",
                            MatchId = 9,
                            isFinished = false
                        },
                        new
                        {
                            ID = 10,
                            AwayCoefficient = 1.95m,
                            AwayCountryId = 7,
                            AwayCountryName = "Italy",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 3.0m,
                            HomeCountryId = 9,
                            HomeCountryName = "Croatia",
                            MatchId = 10,
                            isFinished = false
                        },
                        new
                        {
                            ID = 11,
                            AwayCoefficient = 3.5m,
                            AwayCountryId = 7,
                            AwayCountryName = "Italy",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.5m,
                            HomeCountryId = 6,
                            HomeCountryName = "Spain",
                            MatchId = 11,
                            isFinished = false
                        },
                        new
                        {
                            ID = 12,
                            AwayCoefficient = 2.95m,
                            AwayCountryId = 8,
                            AwayCountryName = "Albania",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 1.85m,
                            HomeCountryId = 9,
                            HomeCountryName = "Croatia",
                            MatchId = 12,
                            isFinished = false
                        },
                        new
                        {
                            ID = 13,
                            AwayCoefficient = 5.6m,
                            AwayCountryId = 12,
                            AwayCountryName = "Slovenia",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.4m,
                            HomeCountryId = 10,
                            HomeCountryName = "England",
                            MatchId = 13,
                            isFinished = false
                        },
                        new
                        {
                            ID = 14,
                            AwayCoefficient = 3.2m,
                            AwayCountryId = 13,
                            AwayCountryName = "Serbia",
                            DrawCoefficient = 3.5m,
                            HomeCoefficient = 1.7m,
                            HomeCountryId = 11,
                            HomeCountryName = "Denmark",
                            MatchId = 14,
                            isFinished = false
                        },
                        new
                        {
                            ID = 15,
                            AwayCoefficient = 8.0m,
                            AwayCountryId = 13,
                            AwayCountryName = "Serbia",
                            DrawCoefficient = 3.0m,
                            HomeCoefficient = 1.6m,
                            HomeCountryId = 10,
                            HomeCountryName = "England",
                            MatchId = 15,
                            isFinished = false
                        },
                        new
                        {
                            ID = 16,
                            AwayCoefficient = 1.95m,
                            AwayCountryId = 11,
                            AwayCountryName = "Denmark",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 3.0m,
                            HomeCountryId = 12,
                            HomeCountryName = "Slovenia",
                            MatchId = 16,
                            isFinished = false
                        },
                        new
                        {
                            ID = 17,
                            AwayCoefficient = 3.5m,
                            AwayCountryId = 11,
                            AwayCountryName = "Denmark",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.5m,
                            HomeCountryId = 10,
                            HomeCountryName = "England",
                            MatchId = 17,
                            isFinished = false
                        },
                        new
                        {
                            ID = 18,
                            AwayCoefficient = 2.95m,
                            AwayCountryId = 13,
                            AwayCountryName = "Serbia",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 1.85m,
                            HomeCountryId = 12,
                            HomeCountryName = "Slovenia",
                            MatchId = 18,
                            isFinished = false
                        },
                        new
                        {
                            ID = 19,
                            AwayCoefficient = 5.6m,
                            AwayCountryId = 17,
                            AwayCountryName = "Poland",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.4m,
                            HomeCountryId = 14,
                            HomeCountryName = "Netherlands",
                            MatchId = 19,
                            isFinished = false
                        },
                        new
                        {
                            ID = 20,
                            AwayCoefficient = 3.2m,
                            AwayCountryId = 16,
                            AwayCountryName = "Austria",
                            DrawCoefficient = 3.5m,
                            HomeCoefficient = 1.7m,
                            HomeCountryId = 15,
                            HomeCountryName = "France",
                            MatchId = 20,
                            isFinished = false
                        },
                        new
                        {
                            ID = 21,
                            AwayCoefficient = 8.0m,
                            AwayCountryId = 16,
                            AwayCountryName = "Austria",
                            DrawCoefficient = 3.0m,
                            HomeCoefficient = 1.6m,
                            HomeCountryId = 14,
                            HomeCountryName = "Netherlands",
                            MatchId = 21,
                            isFinished = false
                        },
                        new
                        {
                            ID = 22,
                            AwayCoefficient = 1.95m,
                            AwayCountryId = 15,
                            AwayCountryName = "France",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 3.0m,
                            HomeCountryId = 17,
                            HomeCountryName = "Poland",
                            MatchId = 22,
                            isFinished = false
                        },
                        new
                        {
                            ID = 23,
                            AwayCoefficient = 3.5m,
                            AwayCountryId = 15,
                            AwayCountryName = "France",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.5m,
                            HomeCountryId = 14,
                            HomeCountryName = "Netherlands",
                            MatchId = 23,
                            isFinished = false
                        },
                        new
                        {
                            ID = 24,
                            AwayCoefficient = 2.95m,
                            AwayCountryId = 16,
                            AwayCountryName = "Austria",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 1.85m,
                            HomeCountryId = 17,
                            HomeCountryName = "Poland",
                            MatchId = 24,
                            isFinished = false
                        },
                        new
                        {
                            ID = 25,
                            AwayCoefficient = 5.6m,
                            AwayCountryId = 21,
                            AwayCountryName = "Ukraine",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.4m,
                            HomeCountryId = 18,
                            HomeCountryName = "Romania",
                            MatchId = 25,
                            isFinished = false
                        },
                        new
                        {
                            ID = 26,
                            AwayCoefficient = 3.2m,
                            AwayCountryId = 20,
                            AwayCountryName = "Slovakia",
                            DrawCoefficient = 3.5m,
                            HomeCoefficient = 1.7m,
                            HomeCountryId = 19,
                            HomeCountryName = "Belgium",
                            MatchId = 26,
                            isFinished = false
                        },
                        new
                        {
                            ID = 27,
                            AwayCoefficient = 8.0m,
                            AwayCountryId = 20,
                            AwayCountryName = "Slovakia",
                            DrawCoefficient = 3.0m,
                            HomeCoefficient = 1.6m,
                            HomeCountryId = 18,
                            HomeCountryName = "Romania",
                            MatchId = 27,
                            isFinished = false
                        },
                        new
                        {
                            ID = 28,
                            AwayCoefficient = 1.95m,
                            AwayCountryId = 19,
                            AwayCountryName = "Belgium",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 3.0m,
                            HomeCountryId = 21,
                            HomeCountryName = "Ukraine",
                            MatchId = 28,
                            isFinished = false
                        },
                        new
                        {
                            ID = 29,
                            AwayCoefficient = 3.5m,
                            AwayCountryId = 19,
                            AwayCountryName = "Belgium",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.5m,
                            HomeCountryId = 18,
                            HomeCountryName = "Romania",
                            MatchId = 29,
                            isFinished = false
                        },
                        new
                        {
                            ID = 30,
                            AwayCoefficient = 2.95m,
                            AwayCountryId = 20,
                            AwayCountryName = "Slovakia",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 1.85m,
                            HomeCountryId = 21,
                            HomeCountryName = "Ukraine",
                            MatchId = 30,
                            isFinished = false
                        },
                        new
                        {
                            ID = 31,
                            AwayCoefficient = 5.6m,
                            AwayCountryId = 23,
                            AwayCountryName = "Turkey",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.4m,
                            HomeCountryId = 22,
                            HomeCountryName = "Portugal",
                            MatchId = 31,
                            isFinished = false
                        },
                        new
                        {
                            ID = 32,
                            AwayCoefficient = 3.2m,
                            AwayCountryId = 24,
                            AwayCountryName = "Czech Republic",
                            DrawCoefficient = 3.5m,
                            HomeCoefficient = 1.7m,
                            HomeCountryId = 1,
                            HomeCountryName = "Georgia",
                            MatchId = 32,
                            isFinished = false
                        },
                        new
                        {
                            ID = 33,
                            AwayCoefficient = 8.0m,
                            AwayCountryId = 24,
                            AwayCountryName = "Czech Republic",
                            DrawCoefficient = 3.0m,
                            HomeCoefficient = 1.6m,
                            HomeCountryId = 22,
                            HomeCountryName = "Portugal",
                            MatchId = 33,
                            isFinished = false
                        },
                        new
                        {
                            ID = 34,
                            AwayCoefficient = 1.95m,
                            AwayCountryId = 1,
                            AwayCountryName = "Georgia",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 3.0m,
                            HomeCountryId = 23,
                            HomeCountryName = "Turkey",
                            MatchId = 34,
                            isFinished = false
                        },
                        new
                        {
                            ID = 35,
                            AwayCoefficient = 3.5m,
                            AwayCountryId = 1,
                            AwayCountryName = "Georgia",
                            DrawCoefficient = 3.4m,
                            HomeCoefficient = 1.5m,
                            HomeCountryId = 22,
                            HomeCountryName = "Portugal",
                            MatchId = 35,
                            isFinished = false
                        },
                        new
                        {
                            ID = 36,
                            AwayCoefficient = 2.95m,
                            AwayCountryId = 24,
                            AwayCountryName = "Czech Republic",
                            DrawCoefficient = 3.7m,
                            HomeCoefficient = 1.85m,
                            HomeCountryId = 23,
                            HomeCountryName = "Turkey",
                            MatchId = 36,
                            isFinished = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
